### ISSUE TITLE
Where do I get the pubnub keys from?

### ISSUE THREAD

**Issue by PanosJee** [resin-io-modules/resin-device-logs#1]
Where do I get the pubnub keys from? I don't see an option in resin.io to connect a pubnub account.

**Comment by jviotti** [comment]
Hi @PanosJee , apologies for the late response. This module is low-level and it's not meant to be used directly. You should use the Resin SDK (https://github.com/resin-io/resin-sdk), which configured this module with the correct pub nub keys for you. You can see logs related documentation here: https://github.com/resin-io/resin-sdk/blob/master/DOCUMENTATION.md#resin.logs.
