### ISSUE TITLE
Uncaught, unspecified "error" event. (PNNetworkIssuesCategory)

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io-modules/resin-device-logs#21]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_18sd)

**Comment by LucianBuzzo** [comment]
Repro for this is simple refreshing the page whilst on the device summary

**Comment by LucianBuzzo** [comment]
If you don't add an event listener, then this line https://github.com/resin-io/resin-device-logs/blob/master/lib/logs.coffee#L90 will cause a thrown error.
See https://github.com/Gozala/events/blob/master/events.js#L53
Is this desired behaviour?

**Comment by emirotin** [comment]
So we've discussed it and decided it's actually OK, the error is there and it's up to the downstream consumer to interpret it.
